# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
#     ports:
#       - 8081:8081
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
    - api  
    ports:
      - "8081:8081"