# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  tgwebapp:
    image: tgwebapp
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    # ports:
    #   - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
